### ISSUE TITLE
Please copy LICENSE from flowbetween

### ISSUE THREAD

**Issue by ctrlcctrlv** [Logicalshift/flo_curves#2]
Sorry to bother you again—

Although it's stated in `Cargo.toml` that this library is Apache2 licensed, I think it's better if you actually distribute the license.

Can you please copy https://github.com/Logicalshift/flowbetween/blob/master/LICENSE to here?

**Comment by Logicalshift** [comment]
Oops, yes: I should have done that when I split the project from FlowBetween. That should be done now.

**Comment by ctrlcctrlv** [comment]
Thank you! It's very much appreciated.

You might be interested in the pattern-along-path work @MatthewBlanchard did for me: https://github.com/mfeq/Qstroke/

We're now tackling variable width stroking for Qstroke. :-)

It's quite possible your code will be borrowed. Likely, I'd say. Obviously w/credit, our code is also Apache2.

Variable stroke-based fonts have always been a dream of mine, and we're quite close.
