### ISSUE TITLE
fill confusion on hand-spock

### ISSUE THREAD

**Issue by mlwilkerson** [Logicalshift/flo_curves#24]
This seems like it might be similar to #23, except that the fix for that one didn't fix this one.

It's happens when taking this Font Awesome Free Regular [`hand-spock`](https://github.com/FortAwesome/Font-Awesome/blob/6.3.0/svgs/regular/hand-spock.svg) SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Free 6.3.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2023 Fonticons, Inc. -->
<path d="M189.7 25.3l6.2 23.2-6.2-23.2zm48.9 28.4l23.2-6.2v0l-23.2 6.2zM161.3 74.3l-23.2 6.2v0l23.2-6.2zm46.5 175.3l-22.1 9.3c4.9 11.6 17.9 17.5 29.9 13.4s18.7-16.7 15.4-28.9l-23.2 6.2zm-51-121.1l-22.1 9.3 22.1-9.3zm-52.4-21.3l9.3 22.1-9.3-22.1zM83.1 159.5L61 168.8h0l22.1-9.3zm5.4 144.9l14.7-18.9L88.6 304.4zm-56.1 7l18.9 14.7h0L32.4 311.4zm7 56.1L24.7 386.5h0l14.7-18.9zm92 71.6l-14.7 18.9 14.7-18.9zm300.1-48.5l23.3 5.8-23.3-5.8zm55.2-220.9l23.3 5.8v0l-23.3-5.8zm-29.1-48.5l5.8-23.3-5.8 23.3zm-48.5 29.1l23.3 5.8v0l-23.3-5.8zM383 255l-23.3-5.8 0 0L383 255zm-2.6-.5l23.6 4.2 0 0-23.6-4.2zM407.4 103l23.6 4.2v0L407.4 103zM375 56.6l-4.2 23.6L375 56.6zM328.6 89L305 84.8v0L328.6 89zM299.5 252.6l-23.6-4.2 0 0 23.6 4.2zm-8 .3l23.2-6.2 0 0-23.2 6.2zM304 488l.5-24-.5 24zm-157-138L161.8 331l-14.7 18.9zM195.9 48.5c8.5-2.3 17.3 2.8 19.6 11.4l46.4-12.3c-9.1-34.2-44.1-54.5-78.3-45.4l12.3 46.4zM184.5 68.1c-2.3-8.5 2.8-17.3 11.4-19.6L183.6 2.1c-34.2 9.1-54.5 44.1-45.4 78.3l46.4-12.3zM231 243.4L184.5 68.1 138.1 80.4l46.5 175.3L231 243.4zM134.7 137.8l51 121.1L230 240.2 179 119.2l-44.2 18.6zm-21-8.5c8.1-3.4 17.5 .4 21 8.5L179 119.2C165.3 86.6 127.7 71.3 95.2 85l18.6 44.2zm-8.5 21c-3.4-8.1 .4-17.5 8.5-21L95.2 85C62.6 98.7 47.3 136.3 61 168.8l44.2-18.6zm76.2 181l-76.2-181L61 168.8l76.2 181 44.2-18.6zM73.8 323.4l58.5 45.5L161.8 331l-58.5-45.5L73.8 323.4zm-22.5 2.8c5.4-7 15.5-8.2 22.5-2.8l29.5-37.9c-27.9-21.7-68.1-16.7-89.8 11.2l37.9 29.5zm2.8 22.5c-7-5.4-8.2-15.5-2.8-22.5L13.5 296.7c-21.7 27.9-16.7 68.1 11.2 89.8l29.5-37.9zm92 71.6l-92-71.6L24.7 386.5l92 71.6 29.5-37.9zM273.9 464c-46.3 0-91.2-15.4-127.7-43.8l-29.5 37.9C161.6 493 216.9 512 273.9 512V464zm30.1 0H273.9v48H304V464zm2.8 0c-.8 0-1.5 0-2.3 0l-1 48c1.1 0 2.2 0 3.3 0V464zm101.5-79.2C396.7 431.3 354.8 464 306.8 464v48c70 0 131.1-47.7 148-115.6l-46.6-11.6zm55.2-220.9L408.3 384.8l46.6 11.6 55.2-220.9-46.6-11.6zm-11.6-19.4c8.6 2.1 13.8 10.8 11.6 19.4l46.6 11.6c8.6-34.3-12.3-69-46.6-77.6l-11.6 46.6zm-19.4 11.6c2.1-8.6 10.8-13.8 19.4-11.6l11.6-46.6c-34.3-8.6-69 12.3-77.6 46.6l46.6 11.6zM406.3 260.8l26.2-104.7-46.6-11.6L359.7 249.2l46.6 11.6zM381.7 280c11.6 0 21.7-7.9 24.6-19.2l-46.6-11.6c2.5-10.1 11.6-17.2 22-17.2v48zm-24.9-29.7c-2.8 15.5 9.2 29.7 24.9 29.7V232c14.1 0 24.8 12.8 22.3 26.7l-47.3-8.4zM383.8 98.8L356.8 250.3l47.3 8.4L431 107.2l-47.3-8.4zm-13-18.6c8.7 1.5 14.5 9.9 13 18.6l47.3 8.4c6.2-34.8-17-68-51.8-74.2l-8.4 47.3zm-18.6 13c1.5-8.7 9.9-14.5 18.6-13L379.2 33c-34.8-6.2-68 17-74.2 51.8l47.3 8.4zM323.2 256.8L352.2 93.2 305 84.8 275.9 248.4l47.3 8.4zM295.5 280c13.6 0 25.3-9.8 27.7-23.2l-47.3-8.4c1.7-9.5 9.9-16.4 19.6-16.4v48zm-27.2-20.9c3.3 12.3 14.4 20.9 27.2 20.9V232c9 0 16.9 6.1 19.2 14.8l-46.4 12.3zM215.5 59.9l52.8 199.2 46.4-12.3L261.9 47.6 215.5 59.9zM328 488c0 13.4-11.1 24.3-24.5 24l1-48c-13.5-.3-24.5 10.5-24.5 24h48zm-24 24c13.3 0 24-10.8 24-24H280c0-13.2 10.7-24 24-24v48zM137.2 349.8c-6.4-15.2 11.6-29 24.6-18.8l-29.5 37.9c26 20.2 61.9-7.3 49.1-37.7l-44.2 18.6z"/></svg>
```

The cutout path that is being subtracted:
```
M640 512V266.8C608.1 221.6 555.5 192 496 192C398.8 192 320 270.8 320 368c0 59.5 29.6 112.1 74.8 144H640z
```

The resulting SVG path, after converting to nonzero fill-rule:

```svg
M13.5 296.7C-8.2 324.6-3.2 364.8 24.7 386.5C34.5 373.9 44.3 361.3 54.1 348.7C47.1 343.3 45.9 333.2 51.3 326.2C38.7 316.4 26.1 306.5 13.5 296.7zM13.5 296.7C26.1 306.5 38.8 316.4 51.4 326.2C56.7 319.2 66.8 318 73.8 323.4C93.3 338.6 112.8 353.7 132.3 368.9C158.3 389.1 194.2 361.6 181.4 331.2C181.4 331.3 181.4 331.2 181.4 331.3C156 271 130.6 210.6 105.2 150.3C90.5 156.4 75.7 162.6 61 168.8C86.4 229.1 111.8 289.5 137.2 349.8C130.8 334.6 148.8 320.8 161.8 331C142.3 315.8 122.8 300.7 103.3 285.5C75.4 263.8 35.2 268.8 13.5 296.7zM24.7 386.5C29.6 380.2 34.5 373.9 39.4 367.6C39.4 367.5 39.4 367.6 39.4 367.5C34.5 373.8 29.6 380.2 24.7 386.5zM24.7 386.5C55.4 410.4 86 434.2 116.7 458.1C161.6 493 216.9 512 273.9 512C283.9 512 294 512 304 512C317.3 512 328 501.2 328 488C328 501.4 316.9 512.3 303.5 512C304.6 512 305.7 512 306.8 512C331.1 512 354.4 506.2 375.1 495.9C363.1 484.5 352.7 471.4 344.2 457.1C332.5 461.6 319.9 464 306.8 464C306 464 305.3 464 304.5 464C291 463.7 280 474.5 280 488C280 474.8 290.7 464 304 464C294 464 283.9 464 273.9 464C227.6 464 182.7 448.6 146.2 420.2C146.1 420.3 146.2 420.2 146.1 420.3C115.4 396.4 84.8 372.6 54.1 348.7C54.2 348.6 54.1 348.7 54.2 348.6C44.4 361.2 34.5 373.9 24.7 386.5zM61 168.8C75.7 162.6 90.5 156.5 105.2 150.3C101.8 142.2 105.6 132.8 113.7 129.3C107.5 114.5 101.4 99.8 95.2 85C62.6 98.7 47.3 136.3 61 168.8zM88.6 304.4C93.4 298.1 98.3 291.8 103.2 285.5C98.3 291.8 93.5 298.1 88.6 304.4zM95.2 85C101.4 99.7 107.6 114.5 113.8 129.2C113.7 129.3 113.8 129.2 113.7 129.3C121.8 125.9 131.2 129.7 134.7 137.8C149.5 131.6 164.2 125.4 179 119.2C165.3 86.6 127.7 71.3 95.2 85zM134.7 137.8C151.7 178.2 168.7 218.5 185.7 258.9C200.5 252.7 215.2 246.4 230 240.2C213 199.9 196 159.5 179 119.2C164.3 125.4 149.5 131.6 134.8 137.8C134.7 137.8 134.8 137.8 134.7 137.8zM138.1 80.5C145.8 78.4 153.6 76.4 161.3 74.3C153.6 76.4 145.8 78.4 138.1 80.5zM138.1 80.5C153.6 138.8 169.1 197.3 184.6 255.7C200.1 251.6 215.5 247.5 231 243.4C215.5 185 200 126.5 184.5 68.1C169 72.2 153.6 76.3 138.1 80.5zM138.2 80.4C153.7 76.3 169.1 72.2 184.6 68.1C184.5 68.1 184.6 68.1 184.5 68.1C182.2 59.6 187.3 50.8 195.9 48.5C191.8 33 187.7 17.6 183.6 2.1C149.4 11.2 129.1 46.2 138.2 80.4zM147 350C151.9 343.7 156.9 337.3 161.8 331C156.9 337.3 152 343.6 147.1 349.9C147 350 147.1 349.9 147 350zM183.6 2.2C187.7 17.7 191.8 33.1 195.9 48.6C195.9 48.5 195.9 48.6 195.9 48.5C204.4 46.2 213.2 51.3 215.5 59.9C233.1 126.3 250.7 192.7 268.3 259.1C271.6 271.4 282.7 280 295.5 280C309.1 280 320.8 270.2 323.2 256.8C332.9 202.3 342.5 147.7 352.2 93.2C336.5 90.4 320.8 87.6 305 84.8C295.3 139.3 285.6 193.9 275.9 248.4C277.6 238.9 285.8 232 295.5 232C304.5 232 312.4 238.1 314.7 246.8C297.1 180.4 279.5 114 261.9 47.6C252.8 13.4 217.8-6.9 183.6 2.2zM185.7 258.9C190.6 270.5 203.6 276.4 215.6 272.3C227.6 268.2 234.3 255.6 231 243.4C223.3 245.5 215.5 247.5 207.8 249.6C200.4 252.7 193.1 255.8 185.7 258.9zM291.5 252.9C299.2 250.8 307 248.8 314.7 246.8C307 248.8 299.2 250.8 291.5 252.9zM305 84.8C320.7 87.6 336.5 90.4 352.2 93.2C353.7 84.5 362.1 78.7 370.8 80.2C373.6 64.5 376.4 48.7 379.3 33C344.4 26.8 311.2 50 305 84.8zM356.8 250.3C359.1 250.7 361.6 251.2 364 251.6C361.6 251.2 359.2 250.7 356.8 250.3C356.7 250.3 356.8 250.3 356.8 250.3zM356.8 250.3C365.8 199.8 374.8 149.3 383.8 98.8C399.5 101.6 415.2 104.4 431.1 107.2C424.7 142.5 418.5 177.9 412.2 213.2C414.5 212 416.8 210.8 419.1 209.6C423.6 191.8 428 173.9 432.5 156.1C434.6 147.5 443.3 142.3 451.9 144.5C460.5 146.6 465.7 155.3 463.5 163.9C460.8 174.8 458 185.8 455.3 196.7C468.4 193.6 482 192 496 192C499.3 192 502.6 192.1 505.9 192.3C507.3 186.7 508.7 181.1 510.1 175.5C518.7 141.2 497.8 106.5 463.5 97.9C429.2 89.3 394.5 110.2 385.9 144.5C377.2 179.4 368.4 214.3 359.7 249.2C362.2 239.1 371.3 232 381.7 232C382.5 232 383.3 232 384.1 232.1C383.3 232.8 382.5 233.5 381.7 234.2C375.8 239.2 370.2 244.7 365 250.5C364.6 250.9 364.3 251.2 364 251.6C361.6 254.3 359.2 257.2 357 260.1C356.3 257 356.2 253.7 356.8 250.3zM370.8 80.2C379.5 81.7 385.3 90.1 383.8 98.8C399.6 101.6 415.3 104.4 431.1 107.2C437.3 72.4 414.1 39.2 379.3 33C376.5 48.8 373.7 64.5 370.9 80.3C370.8 80.2 370.9 80.3 370.8 80.2zM383.8 98.8C383.8 98.8 383.7 98.8 383.8 98.8zM407.4 103C415.3 104.4 423.1 105.8 431.1 107.2C423.1 105.8 415.3 104.4 407.4 103z
```

Which looks like this:
![hand-spock-regular-cutout-circle](https://user-images.githubusercontent.com/11575183/231622849-61da1829-b5b9-484a-bce9-28da2183b578.png)

You can see that the fill looks wrong where the fourth and fifth fingers overlap (on the right).

This was done using `flo_curves` 0.7.1.

I did the `graph_path_svg_string()` thing, but I'm not sure what to make of it:
<img width="1090" alt="diag" src="https://user-images.githubusercontent.com/11575183/231623924-48b22bb5-55a7-4208-899e-223bf33ff08a.png">

**Comment by Logicalshift** [comment]
Looking at the debug output, I think the problem is that the input shape is self-intersecting, and the path arithmetic functions all require the input shapes to be non-self-intersecting. The `path_remove_interior_points()` and `path_remove_overlapped_points()` can be used together to generate non self-intersecting paths.

The usual way is to use `path_remove_interior_points()` on each subpath, then `path_remove_overlapped_points()` on the path generated by combining the results - it's also possible to combine the output of `path_remove_interior_points()` with the other arithmetic operations to create other effects.

This was a design decision I made quite a while ago for a couple of reasons: it makes it possible to skip a possibly expensive and often unnecessary step when it's already known that a path does not self-intersect, and it makes it possible to generate particular results more consistently than using a winding rule (eg, `path_sub()` will always cut a hole in a path while with a winding rule it's not always clear if a new subpath will be filled, empty or both)

This is definitely a bit unintuitive at the moment: I've been trying to think of some ways to make the requirements more obvious and a bit easier to apply for someone who is expecting the more usual winding rules to apply.

**Comment by mlwilkerson** [comment]
Thanks. I'll give that a try, fixing up the self-intersections. I do remember reading that about the expectation that paths should not be self-intersecting. I made a bad assumption that mine weren't. Shoulda confirmed!

Thanks again.

**Comment by mlwilkerson** [comment]
Still scratching at this problem here and there...

I thought I understood what you meant by this...

> The usual way is to use path_remove_interior_points() on each subpath, then path_remove_overlapped_points() on the path generated by combining the results

...however, I think maybe I don't after all.

Here's how I'm trying to make sense of it. Could correct my interpretation?

Here are a couple of possible interpretations:
1. There are two _subpaths_: the `hand-spock` path and the cutout path. If so, then the meaning is: use `path_remove_interior_points()` on each of those, and then after subtracting the cutout from `hand-spock`, use `path_remove_overlapped_points()` on the result of that subtraction.
2. Each chunk of path data from some `M` to the next `z` is a subpath. The path data for `hand-spock` includes _several_ of those; the cutout has only one. The meaning would be: iterate through each of these subpaths in `hand-spock`, applying `path_remove_overlapped_points()` to each, then do the same for the cutout, then subtract the cutout from `hand-spock`, and finally apply `path_remove_overlapped_points()` from the result of that subtraction.

Is one those what you mean?

I've tried lots of different things and haven't got it to work yet, so that makes me question whether I've understood correctly, or whether there's possibly more going on with this `hand-spock` than these methods will resolve.

Another investigation I tried:

Use `path_remove_interior_points()` on the main path (i.e. the `d` attribute from the `hand-spock` SVG above), and then just subtract the cutout. I got the debug graph SVG from that. (Attached a zip of that debug SVG, and here are a couple of screenshots):

<img width="861" alt="CleanShot 2023-10-16 at 11 08 55@2x" src="https://github.com/Logicalshift/flo_curves/assets/11575183/c4acf1d2-b357-4b89-b153-a40f3d99ec5c">

[hand-spock-remove-interior.zip](https://github.com/Logicalshift/flo_curves/files/12920520/hand-spock-remove-interior.zip)

I can see that `path_remove_interior_points()` definitely cleaned up a lot of stuff, but it appears that there's just one more point that it's getting confused by. Here's a zoomed in screenshot:

![CleanShot 2023-10-16 at 11 23 49@2x](https://github.com/Logicalshift/flo_curves/assets/11575183/ef127b66-4807-4763-bbc3-e45cd623f516)

It looks like the cutout path intersects that diagonal line indicated by the red arrow. I'm not sure whether that diagonal line is debugging metadata from your code, or if it's actually a remaining part of the `hand-spock` path, even after `path_remove_interior_points()`. It seems like the latter, so that the dot pointed at by the red arrow is an erroneous intersection, which produces unexpected results when doing the subtract operation.

So I tried applying `path_remove_interior_points()` a second time on `hand-spock`, just to see what would happen. Would it get rid of that extra diagonal line, and thus the erroneous intersection point? But that went too far:

<img width="846" alt="CleanShot 2023-10-16 at 11 34 50@2x" src="https://github.com/Logicalshift/flo_curves/assets/11575183/5ac96cc0-def4-42c6-98fc-a1b41fbc48fd">

The subtract operation is now correct, but only after removing _too much_ from `hand-spock`.

I'm stumped as to how to proceed. If you have any suggestions, I'd be grateful.

**Comment by mlwilkerson** [comment]
On closer examination of the original `hand-spock`, I see those extra lines in there, like that diagonal where the red arrow is pointing.

In this screenshot, the red arrow is pointing at about the same place as it's pointing in the previous screenshots. Looking closely, I can see a white hair line cutting across the black fill.

![CleanShot 2023-10-16 at 12 20 52@2x](https://github.com/Logicalshift/flo_curves/assets/11575183/92a4a543-39bb-4dd9-912a-3441f4fbd88c)

So this leads me to think that all of the `path_remove_interior_points()` stuff _is_ working as expected here. And the problem is my bad assumptions about the original SVG. It's not just that it has some self-intersection. It's also that it's not even solidly filled throughout. It has those breaks where the hair lines are.

**Comment by mlwilkerson** [comment]
I'm gonna close this because clearly not an issue with flo_curves. My remaining questions are about understanding and using flo_curves better to deal with these problem cases that come up from time to time.
